"""penambahan atribut meja

Revision ID: 18280bcc1080
Revises: ff1a5e56c664
Create Date: 2025-11-19 15:20:23.767670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18280bcc1080'
down_revision: Union[str, Sequence[str], None] = 'ff1a5e56c664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meja', sa.Column('tipe_meja', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meja', 'tipe_meja')
    # ### end Alembic commands ###
