"""empty message

Revision ID: 3e94c502e9ea
Revises: 8538d1aaf8da
Create Date: 2025-11-14 13:58:36.332784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e94c502e9ea'
down_revision: Union[str, Sequence[str], None] = '8538d1aaf8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum('tersedia', 'tidaktersedia', name='statusmeja')
    status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('meja', sa.Column('status', sa.Enum('tersedia', 'tidaktersedia', name='statusmeja'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meja', 'status')
    
    status_enum = sa.Enum('tersedia', 'tidaktersedia', name='statusmeja')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
