"""empty message

Revision ID: 472c1b09f311
Revises: ec4dfaff0b77
Create Date: 2025-11-06 15:13:52.928100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472c1b09f311'
down_revision: Union[str, Sequence[str], None] = 'ec4dfaff0b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meja',
    sa.Column('meja_id', sa.Integer(), nullable=False),
    sa.Column('kode_meja', sa.String(), nullable=False),
    sa.Column('kapasitas', sa.Integer(), nullable=False),
    sa.Column('lokasi', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('meja_id')
    )
    op.create_index(op.f('ix_meja_kode_meja'), 'meja', ['kode_meja'], unique=True)
    op.create_index(op.f('ix_meja_meja_id'), 'meja', ['meja_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('no_telp', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'reservationStaff', 'waiter', 'customer', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meja_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_reservasi', sa.DATE(), nullable=False),
    sa.Column('jam_reservasi', sa.Time(), nullable=False),
    sa.Column('jumlah_orang', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('menunggu', 'berhasil', 'dibatalkan', name='reservationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['meja_id'], ['meja.meja_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index(op.f('ix_reservation_reservation_id'), 'reservation', ['reservation_id'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('feedback_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.reservation_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_feedback_feedback_id'), 'feedback', ['feedback_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('menunggu', 'berhasil', 'gagal', name='paymentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.reservation_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_feedback_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_reservation_reservation_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_meja_meja_id'), table_name='meja')
    op.drop_index(op.f('ix_meja_kode_meja'), table_name='meja')
    op.drop_table('meja')
    # ### end Alembic commands ###
